"""remove apellidos from clientprofile

Revision ID: 0b4c25361aa2
Revises: b2c3d4e5f6a7
Create Date: 2026-04-05 09:52:45.056282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4c25361aa2'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientprofile', 'apellidos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientprofile', sa.Column('apellidos', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
